version: '3'
services:
  nginx:
    build: Multi_Page_WebApp/services/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on: 
      - flask_app
      - panel_app
  
  message_broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  
  message_dispatcher:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/message_dispatcher/Dockerfile
    restart: on-failure
    environment: 
      - BROKER_HOSTNAME=message_broker
    depends_on: 
      - message_broker

  python_worker:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/python_worker/Dockerfile
    restart: on-failure
    environment: 
      - BROKER_HOSTNAME=message_broker
    depends_on: 
      - message_broker
      - message_dispatcher
    volumes:
      - ./Multi_Page_WebApp/instance:/usr/src/app/instance

  mosaic_worker:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/mosaic/Dockerfile
    restart: on-failure
    environment: 
      - BROKER_HOSTNAME=message_broker
    depends_on: 
      - message_broker
      - message_dispatcher
    volumes:
      - ./Multi_Page_WebApp/instance:/usr/src/app/instance
      
  flask_app:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/flask/Dockerfile.dev
    env_file: ${FLASK_CONFIG}
    environment: 
      - BROKER_HOSTNAME=message_broker
    image: netcdf_editor_flask_app:latest 
    expose:
      - 5000
    depends_on: 
      - message_broker
    cap_add:
      - SYS_PTRACE
    entrypoint: flask run
    volumes:
      - ./Multi_Page_WebApp:/usr/src/app
  
  panel_app:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/panel/Dockerfile.dev
    env_file: ${PANEL_CONFIG}
    environment: 
      - BROKER_HOSTNAME=message_broker
    image: netcdf_editor_panel_app:latest
    expose: 
      - 5006
    depends_on: 
      - message_broker
    volumes:
       - ./Multi_Page_WebApp:/usr/src/app

volumes:
  instance_storage:

