DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS data_file;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE data_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  filename TEXT NOT NULL,
  filepath TEXT NOT NULL,
  longitude TEXT,
  latitude TEXT,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);