from ubuntu

# Needed for mpich so doesnt prompt questions
ENV DEBIAN_FRONTEND noninteractive
ENV H5DIR /usr/local/hdf5
ENV NCDIR /usr/local/netcdf

RUN apt update && \
    apt install -y perl make m4 mpich subversion wget curl zlib1g-dev libcurl4-gnutls-dev \
    nco python3 python3-pip uuid && python3 -m pip install netcdf4 scipy \
    && ln -s /usr/bin/make /usr/bin/gmake

RUN cpan install URI

# Download source files
RUN mkdir /src && cd /src && \
    wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/src/hdf5-1.12.0.tar.gz

WORKDIR /src
RUN  tar -xvzf hdf5-1.12.0.tar.gz \
    && rm hdf5-1.12.0.tar.gz
WORKDIR /src/hdf5-1.12.0 
RUN CC=/usr/bin/mpicc  ./configure --prefix=${H5DIR} --enable-parallel --with-zlib
RUN make 
RUN make install

WORKDIR /src
RUN wget https://github.com/Unidata/netcdf-c/archive/v4.7.4.tar.gz && tar -xvzf  v4.7.4.tar.gz && rm -rf  v4.7.4.tar.gz
RUN cd netcdf-c-4.7.4 \
    && CC=/usr/bin/mpicc CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib   ./configure --enable-parallel-tests --prefix=${NCDIR} --enable-remote-fortran-bootstrap\
    && make install

RUN svn co http://forge.ipsl.jussieu.fr/ioserver/svn/XIOS/trunk XIOS
# COPY XIOS_arch_file.env XIOS/arch/arch-GCC_LINUX.env
# COPY arch-linux_ubuntu.fcm XIOS/arch/arch-GCC_LINUX.fcm
# COPY arch-linux_ubuntu.path XIOS/arch/arch-GCC_LINUX.path
COPY arch-linux_ubuntu* XIOS/arch/

RUN cd XIOS && \
     ./make_xios --arch linux_ubuntu --jobs 8

RUN svn co http://forge.ipsl.jussieu.fr/igcmg/svn/TOOLS/MOSAIX MOSAIX
RUN sed -i '/-L%{XIOS_DIR}\/lib/c\%LD_FLAGS         -L%{XIOS_DIR}/lib -lxios %BASE_LD %ARCH_LD' MOSAIX/bld.cfg
RUN cd MOSAIX && ./make_mosaix
ENV LD_LIBRARY_PATH=$NCDIR/lib:$H5DIR/lib:/src/XIOS/lib\
    PATH=$NCDIR/bin:$PATH \
    R_IN=${HOME}/Scratch/IGCM \
    TMPDIR=${HOME}/Scratch/TMP \
    SUBMIT_DIR=$(pwd) \
    MpiRun="/usr/bin/mpirun -n 1" \
    PyRun=""
COPY create_weights.patch Runoff.patch /src/MOSAIX/
RUN cd MOSAIX && patch < Runoff.patch && patch < create_weights.patch
COPY ORCA2.3_coordinates_mask.nc ${HOME}/Scratch/IGCM/OCE/NEMO/ORCA2.3/
COPY LMD9695_grid.nc ${HOME}/Scratch/IGCM/ATM/GRID/